### ISSUE TITLE
Is this currently not available?

### ISSUE THREAD

**Issue by VTFLAB** [CactusDev/glimesh-chat#3]
The token is correct, but I can't connect properly and get an error message.  
  
`Error: Request failed with status code 401
    at createError (/workspaces/.../backend/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/workspaces/.../backend/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/workspaces/.../backend/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {`

**Comment by VTFLAB** [comment]
It seems that there was just a problem with the Glimesh server issuing the tokens, after a few hours, I tried again and the authentication went through fine!
